from __future__ import annotations

WL_STATUS_ACTIVE = "ACTIVE"
WL_STATUS_SUSPENDED = "SUSPENDED"
WL_STATUS_ERROR = "ERROR"

WL_REQUEST_STATUS_PENDING = "PENDING"
WL_REQUEST_STATUS_ACCEPTED = "ACCEPTED"
WL_REQUEST_STATUS_REJECTED = "REJECTED"
WL_REQUEST_STATUS_CANCELLED = "CANCELLED"

WL_PLAN_TRIAL = "TRIAL"
WL_PLAN_BASIC = "BASIC"
WL_PLAN_PLUS = "PLUS"
WL_PLAN_PRO = "PRO"
WL_PLAN_COMMUNITY = "COMMUNITY"
WL_PLAN_MANUAL = "MANUAL"

WL_SUBSCRIPTION_TRIALING = "TRIALING"
WL_SUBSCRIPTION_MANUAL = "MANUAL"
WL_SUBSCRIPTION_EXPIRED = "EXPIRED"

WL_CACHE_STATUS_VALID = "VALID"
WL_CACHE_STATUS_INVALID = "INVALID"
WL_CACHE_STATUS_FAILED = "FAILED"

WL_SEED_STATUS_PENDING = "PENDING"
WL_SEED_STATUS_SENT_TO_CACHE = "SENT_TO_CACHE"
WL_SEED_STATUS_CACHED = "CACHED"
WL_SEED_STATUS_FAILED = "FAILED"
WL_SEED_STATUS_EXPIRED = "EXPIRED"
