from telegram import InlineKeyboardButton, InlineKeyboardMarkup

# Dictionary of interface messages in multiple languages
MESSAGES = {
    "uz": {
        "greeting": (
            "Assalomu alaykum 👋\n"
            "{first_name}\n\n"
            "<blockquote>Pdf va audio kitoblar botiga xush kelibsiz!\n"
            "Pastdagi menulardan birini tanlang:</blockquote>"
        ),
        "start_menu_title": "Assalomu alaykum, {name} 👋",
        "start_menu_subtitle": "Kerakli bo‘limni tanlang 👇",
        "menu_other_subtitle": "Qo‘shimcha imkoniyatlar 👇",
        "menu_search_books": "🔎 Kitob qidirish",
        "menu_text_to_voice": "🎙️ Matndan ovoz",
        "menu_audio_tools": "🎙️ Audio vositalar",
        "menu_audio_tools_placeholder": "Audio vositani tanlang 👇\n🎙️ Text to Audio yoki 🎛️ Audio muharriri.",
        "menu_audio_text_to_audio": "🎙️ Text to Audio",
        "menu_audio_converter": "🎛️ Audio muharriri",
        "menu_audio_converter_placeholder": "Audio muharriri funksiyasini tanlang 👇\n✂️ Kesish yoki 🎧➡️🎙️ Ovozli xabarga o‘tkazish.",
        "menu_audio_cutter": "✂️ Audioni kesish",
        "menu_audio_to_voice": "🎧➡️🎙️ Voice xabarga o‘tkazish",
        "menu_other_functions": "🛠️ Boshqa funksiyalar",
        "menu_document_tools": "📄 Hujjat vositalari",
        "menu_document_tools_placeholder": "Hujjat vositasini tanlang 👇\n📄 PDF Maker yoki 🗜️ PDF Compressor.",
        "menu_pdf_maker": "🤖 AI PDF Maker",
        "menu_pdf_editor": "🧰 PDF muharriri",
        "menu_sticker_tools": "🧩 Sticker vositalar",
        "menu_pdf_compressor": "🗜️ PDF siqish",
        "menu_request_book": "📝 Kitob so‘rash",
        "menu_favorites": "⭐ Sevimlilar",
        "menu_upload": "⬆️ Kitob yuklash",
        "menu_contact_admin": "📞 Admin bilan aloqa",
        "menu_myprofile": "👤 Mening profilim",
        "menu_top_books": "🔥 Top kitoblar",
        "menu_top_users": "🏆 Top foydalanuvchilar",
        "menu_help": "❓ Yordam",
        "menu_back": "⬅️ Orqaga",
        "menu_search_prompt": "🔎 Kitob nomi yoki muallifni yuboring.\n\nMasalan:\n<blockquote>Atomic Habits\nShaytanat\nIkki eshik orasi</blockquote>\n\n💡 Eng yaxshi natija uchun to‘liq nom yoki muallif bilan yozing.",
        "menu_search_click_first_hint": "📚 Avval `🔎 Kitob qidirish` tugmasini bosing.\nKeyin kitob nomini oddiy matn sifatida yuboring.",
        "menu_search_image_hint": "🖼️ Hozircha rasm ichidagi kitob nomini o‘qib qidira olmayman.\n🔎 Iltimos, kitob nomini matn ko‘rinishida yuboring.\n✨ Keyinroq rasm tavsifi funksiyasi qo‘shilishi mumkin.",
        "menu_request_prompt": "📝 Bu bo‘lim endi mavjud emas.",
        "contact_admin_info": "📞 Admin bilan aloqa\n\nSavol, taklif yoki muammo bo‘lsa, bot egasi bilan bevosita bog‘lanishingiz mumkin.",
        "contact_admin_button": "👤 Adminga yozish",
        "menu_use_command_hint": "👇 Bu bo‘limni pastdagi menyu orqali oching.",
        "menu_flow_cancelled": "❌ Oldingi jarayon bekor qilindi.",
        "group_promo_short": "🌍 Kitobxonlar hamjamiyatiga qo‘shiling: {group}",
        "blocked": "❌ Siz bloklangansiz.",
        "not_found": "❌ Bu nom bo‘yicha kitob topilmadi.\n💡 Nomni aniqroq yozing (muallif yoki to‘liq nom) va qayta urinib ko‘ring.",
        "error": "⚠️ Kutilmagan xatolik yuz berdi.\n🔁 Iltimos, qayta urinib ko‘ring yoki menyudan bo‘limni qayta oching.",
        "error_notified": "⚠️ Xatolik yuz berdi, egasi xabardor qilindi.\n🔁 Iltimos, birozdan keyin qayta urinib ko‘ring.",
        "processing_general": "⏳ So‘rovingiz qayta ishlanmoqda...",
        "processing_search": "🔎 Qidiryapman... bir necha soniya kuting.",
        "admin_only": "🚫 Sizga bu buyruqni ishlatishga ruxsat berilmagan.",
        "owner_only": "👑 Bu buyruq faqat bot egasi uchun.",
        "admin_broadcast_prompt": "📣 Barcha foydalanuvchilarga yuboriladigan xabarni yuboring.\nBekor qilish: cancel",
        "admin_user_search_prompt": "👤 Ism, username yoki user ID yuboring (to‘liq/qisman).\nBekor qilish: cancel",
        "bot_paused": "⏳ Hozir botda yangilanishlar ketmoqda. Iltimos, biroz kutib turing. 😊❤️\n🕒 Boshlangan vaqt: {time}",
        "bot_paused_on": "⏸️ Bot pauzaga qo‘yildi. 🕒 {time}",
        "bot_paused_off": "▶️ Bot qayta ishga tushdi.",
        "send_doc": "⚠️ Iltimos, hujjat faylini yuboring.",
        "duplicate": "⚠️ Nusxa e'tiborsiz qoldirildi:",
        "es_unavailable": "⚠️ Elasticsearch mavjud emas, kitob faqat lokal saqlandi.",
        "saved": "✅ Saqlandi:",
        "upload_adult_filtered": "⚠️ 18+ yoki kattalar mazmuni bor kitob yuklanmadi:",
        "upload_file_type_filtered": "⚠️ Bu fayl turi kitob yuklash uchun qabul qilinmaydi: {file_name}\n📚 Ruxsat etilgan formatlar: {formats}",
        "upload_inactive": "⚠️ Yuklash rejimi faol emas yoki sizga ruxsat berilmagan.",
        "upload_activated": "📥 Yuklash rejimi yoqildi. Kitob fayllarini yuboring.",
        "not_authorized": "❌ Sizga bu buyruqni ishlatishga ruxsat berilmagan.",
        "results_for": "📖 Natijalar",
        "results_header": "📚 {total} ta natija topildi",
        "results_pick_hint": "Kerakli kitobni tanlang:",
        "results_page_line": "Sahifa {page}/{pages}",
        "results_item_line": "{index}. {title}",
        "random_results_query": "🎲 Tasodifiy kitoblar",
        "top_header": "🔥 Top kitoblar (sahifa {page}/{pages}, jami {total})",
        "top_empty": "❌ Top roʻyxat bo‘sh.",
        "choose_language": "👋 Xush kelibsiz! Tilni tanlang:",
        "group_private_start_required": "🔐 Guruhda botdan foydalanish uchun avval botni bir marta shaxsiy chatda ishga tushiring.",
        "group_private_start_button": "🚀 Botni ochish",
        "group_private_start_ready": "✅ Ajoyib! Siz botni ishga tushirdingiz.\n🌐 Endi tilingizni tanlang:",
        "group_choose_language": "🌐 Guruh uchun tilni tanlang:",
        "group_search_ready": "📚 Qidirmoqchi bo'lgan kitob nomini yuboring.\n↩️ Iltimos, shu xabarga javob qilib yozing.",
        "book_unavailable": "❌ Kitob mavjud emas (lokal yoki keshda yo'q).",
        "book_unavailable_no_file": "❌ Bu kitob ES da bor, lekin fayl yo'q (file_id va lokal fayl topilmadi).",
        "book_unavailable_file_missing": "❌ Lokal fayl topilmadi. Iltimos, keyinroq urinib ko'ring.",
        "book_unavailable_send_failed": "❌ Faylni yuborib bo'lmadi. Iltimos, keyinroq urinib ko'ring.",
        "inline_book_upload_description": "Kitobni yuborish uchun bosing",
        "inline_book_info_only": "Faqat kitob ma’lumoti",
        "book_action_favorite": "⭐ Sevimli",
        "book_action_remove_favorite": "❌ Olib tashlash",
        "book_action_rename": "✏️ Nomini o‘zgartirish",
        "book_action_delete": "🗑️ Kitobni o‘chirish",
        "enter_specific": "⚠️ Qidiruv uchun aniqroq kitob nomini yuboring.\n💡 Masalan: `Atomic Habits` yoki `Shaytanat 1`.",
        "book_not_found": "⚠️ Kitob topilmadi.\n💡 Nomni aniqroq yozib yana yuboring.",
        "after_book_group_invite": "📚 Yangi kitoblar, muhokamalar va foydali tavsiyalar uchun guruhimizga qo‘shiling.",
        "after_book_group_button": "🌍 Guruhga qo‘shilish",
        "audit_failed": "⚠️ Audit bajarilmadi, loglarni tekshiring.",
        "audit_title": "📊 Audit hisobot",
        "audit_section_system": "🧰 Tizim",
        "audit_section_books": "📚 Kitoblar",
        "audit_section_users": "👤 Foydalanuvchilar",
        "audit_section_requests": "📩 So‘rovlar",
        "audit_section_uploads": "⬆️ Upload so‘rovlar",
        "audit_section_favorites": "⭐ Sevimlilar",
        "audit_section_events": "🧾 Umumiy hodisalar",
        "audit_section_reactions": "💬 Reaksiyalar",
        "audit_section_today": "📅 Bugun",
        "audit_books_json": "DB dagi kitoblar",
        "audit_books_total": "Kitoblar (jami)",
        "audit_books_indexed": "Indekslangan",
        "audit_books_downloads_total": "Yuklab olingan (jami)",
        "audit_books_searches_total": "Qidiruvlar (jami)",
        "audit_books_es": "ES dagi kitoblar",
        "audit_unindexed": "Indekslanmagan",
        "audit_total_users": "Jami foydalanuvchilar",
        "audit_users_blocked": "Bloklangan foydalanuvchilar",
        "audit_users_allowed": "Ruxsat berilgan foydalanuvchilar",
        "audit_joined_today": "Bugun qo'shilgan",
        "audit_left_today": "Bugun chiqib ketgan",
        "audit_searches_today": "Bugun qidiruvlar",
        "audit_buttons_today": "Tugma orqali kitoblar",
        "audit_status_up": "Ishlayapti",
        "audit_status_down": "Ishlamayapti",
        "audit_es_status": "ES holati",
        "audit_es_health": "ES health",
        "audit_db_status": "DB holati",
        "audit_db_error": "DB xatolik",
        "audit_favorites_count": "Sevimlilar soni",
        "audit_favorites_total": "Sevimlilar (jami)",
        "audit_favorites_added": "Sevimliga qo‘shilgan (jami)",
        "audit_favorites_removed": "Sevimlidan o‘chirilgan (jami)",
        "audit_recents_count": "Yaqinda ochilganlar soni",
        "audit_requests_count": "So‘rovlar soni",
        "audit_requests_open": "Yangi (open)",
        "audit_requests_seen": "Ko‘rildi",
        "audit_requests_done": "Bajarildi",
        "audit_requests_no": "Mumkin emas",
        "audit_upload_requests_count": "Upload so‘rovlari soni",
        "audit_upload_open": "Yangi (open)",
        "audit_upload_accept": "Qabul qilingan",
        "audit_upload_reject": "Rad etilgan",
        "audit_removed_users_count": "O‘chirilgan foydalanuvchilar",
        "audit_analytics_days": "Analytics kunlari",
        "audit_unindexed_list": "❌ Indekslanmagan kitoblar:",
        "audit_search_total": "Qidiruvlar (jami)",
        "audit_download_total": "Yuklab olish (jami)",
        "audit_requests_created": "So‘rovlar yaratilgan (jami)",
        "audit_requests_cancelled": "So‘rovlar bekor qilingan (jami)",
        "audit_requests_seen_total": "So‘rovlar ko‘rilgan (jami)",
        "audit_requests_done_total": "So‘rovlar bajarilgan (jami)",
        "audit_requests_no_total": "So‘rovlar rad etilgan (jami)",
        "audit_upload_accept_total": "Upload qabul qilingan (jami)",
        "audit_upload_reject_total": "Upload rad etilgan (jami)",
        "audit_reaction_like": "👍 Reaksiya (jami)",
        "audit_reaction_dislike": "👎 Reaksiya (jami)",
        "audit_reaction_berry": "🍓 Reaksiya (jami)",
        "audit_reaction_whale": "🐳 Reaksiya (jami)",
        "audit_reaction_current_like": "👍 Hozirgi (unikal)",
        "audit_reaction_current_dislike": "👎 Hozirgi (unikal)",
        "audit_reaction_current_berry": "🍓 Hozirgi (unikal)",
        "audit_reaction_current_whale": "🐳 Hozirgi (unikal)",
        "audit_today_joined": "Bugun qo‘shilgan",
        "audit_today_left": "Bugun chiqib ketgan",
        "audit_today_searches": "Bugun qidiruvlar",
        "audit_today_downloads": "Bugun yuklab olish",
        "broadcast_usage": "📢 Admin Control menyusidan Broadcast bo‘limini ochib, xabar yuboring.",
        "broadcast_done": "✅ {sent} foydalanuvchiga yuborildi. {blocked} bloklangan foydalanuvchi belgilandi.",
        "prune_started": "⏳ Tozalash boshlandi. Yakunlangach xabar beraman.",
        "prune_done": "✅ {removed} bloklangan foydalanuvchi tozalandi. Qolgan aktivlar: {active}",
        "missing_title": "⚠️ Yetishmayotgan fayllar:",
        "missing_none": "✅ Yetishmayotgan fayl topilmadi.",
        "missing_item": "• {title} — {reason}",
        "missing_reason_no_file_id": "file_id yo'q",
        "missing_reason_local_missing": "lokal fayl topilmadi",
        "missing_confirm_prompt": "⚠️ O'chirishni tasdiqlash uchun 60 soniya ichida Admin Control menyusidagi Missing Confirm tugmasini bosing.",
        "missing_confirm_expired": "⏳ Tasdiqlash vaqti tugadi. Admin Control menyusidan Missing Files bo‘limini qayta oching.",
        "missing_deleted": "✅ O'chirildi: JSON={json}, ES={es}, ES xatolar={es_failed}.",
        "chat_id_info": "Chat ID: {chat_id}\nType: {chat_type}\nUser ID: {user_id}",
        "delete_confirm": "⚠️ O'chirishni tasdiqlash uchun 15 soniya ichida yana bosing.",
        "delete_done": "🗑️ O'chirildi: {title}\nDB={db}, ES={es}, ES xatolar={es_failed}{local}",
        "delete_local_deleted": " | lokal fayl o'chirildi",
        "delete_local_missing": " | lokal fayl topilmadi",
        "user_search_usage": "👤 Admin Control menyusidagi Search Users bo‘limidan ism, username yoki user ID (to‘liq/qisman) yuboring.",
        "user_bonus_prompt_add": "➕ {name} uchun bonus qo‘shish.\nIltimos, miqdorni yuboring (masalan: 10). Bekor qilish: cancel",
        "user_bonus_prompt_del": "➖ {name} uchun bonus kamaytirish.\nIltimos, miqdorni yuboring (masalan: 5). Bekor qilish: cancel",
        "user_bonus_invalid": "❌ Noto‘g‘ri miqdor. Faqat musbat son yuboring.",
        "user_bonus_cancelled": "✅ Bekor qilindi.",
        "user_bonus_added": "✅ Bonus qo‘shildi: {name} (+{amount}). Yangi bonus: {bonus}",
        "user_bonus_removed": "✅ Bonus kamaytirildi: {name} (-{amount}). Yangi bonus: {bonus}",
        "bonus_received_notice": "🎉 Tabriklaymiz! Siz {amount} bonus tanga oldingiz.\n👤 Mening profilim bo‘limida statistikangiz, 🪙 tangalaringiz va 🎁 bonuslaringizni ko‘rishingiz mumkin.",
        "user_search_empty": "❌ Foydalanuvchi topilmadi.",
        "user_search_title": "👤 Natijalar: '{query}'",
        "user_results_header": "👤 Foydalanuvchi natijalari: {total} ta",
        "user_results_pick_hint": "Kerakli foydalanuvchini tanlang:",
        "user_not_found": "❌ Foydalanuvchi topilmadi.",
        "stop_disabled_notice": "✅ Siz yana botdan foydalanishingiz mumkin. Pastdagi menyudan kerakli bo‘limni tanlang.",
        "upload_allowed_notice": "✅ Sizga kitob yuklashga ruxsat berildi.",
        "delete_allowed_notice": "✅ Sizga kitoblarni o'chirishga ruxsat berildi.",
        "audio_allowed_notice": "✅ Sizga audiokitob qo‘shishga ruxsat berildi.",
        "book_rename_private_only": "✏️ Kitob nomini o‘zgartirish faqat shaxsiy chatda mumkin.",
        "help_text": "📚 Yordam\nBotdan qulay foydalanish uchun pastdagi menyudan bo‘lim tanlang.\n──────────\n🔎 Kitob qidirish — kitob nomi yoki muallif bo‘yicha qidiring.\n🎙️ Matndan ovoz — matndan audio yarating.\n👤 Mening profilim — statistikangiz va tangalaringizni ko‘ring.\n🛠️ Boshqa funksiyalar — PDF vositalari, top ro‘yxatlar, sevimlilar, kitob so‘rash va boshqalar.\n──────────\n🌐 Tilni o‘zgartirish: `Language` bo‘limi.",
        "thanks_reply": "Arzimaydi 😊 Yordamim tekkan bo‘lsa, xursandman.",
        "summary_coming_soon": "🧠 AI kitob xulosasi tez orada qo‘shiladi.",
        "summary_button": "🧠 Xulosa",
        "summary_choose_mode": "🧠 Xulosa turini tanlang:",
        "summary_mode_short": "Qisqa",
        "summary_mode_detailed": "Batafsil",
        "summary_mode_points": "Punktlar",
        "summary_mode_cancel": "Bekor qilish",
        "summary_working": "⏳ Kitob xulosasi tayyorlanmoqda...",
        "summary_ready_title": "🧠 Kitob xulosasi ({mode})",
        "summary_cached_note": "⚡ Oldindan tayyorlangan xulosa",
        "summary_already_running": "⏳ Bu kitob uchun xulosa allaqachon tayyorlanmoqda.",
        "summary_book_missing": "❌ Kitob topilmadi.",
        "summary_no_source": "❌ Bu kitob uchun fayl manbasi topilmadi.",
        "summary_download_failed": "❌ Xulosa uchun faylni yuklab bo‘lmadi.",
        "summary_download_too_big": "❌ Fayl juda katta. Xulosa qilish uchun lokal nusxa (path) kerak.",
        "summary_extract_failed": "❌ Matnni ajratib bo‘lmadi. Fayl turi qo‘llab-quvvatlanmasligi mumkin.",
        "summary_empty_text": "❌ Fayldan o‘qiladigan matn topilmadi (skan PDF bo‘lishi mumkin).",
        "summary_ai_unavailable": "⚠️ AI xulosa xizmati hozir ishlamayapti. Keyinroq urinib ko‘ring.",
        "summary_error": "⚠️ Xulosa tayyorlashda xatolik yuz berdi.",
        "summary_progress_prefix": "🧠 Xulosa tayyorlanmoqda",
        "summary_progress_elapsed": "⏱️ {seconds}s",
        "summary_stage_start": "boshlanmoqda",
        "summary_stage_cache": "kesh tekshirilmoqda",
        "summary_stage_source": "fayl manbasi tekshirilmoqda",
        "summary_stage_download": "fayl yuklab olinmoqda",
        "summary_stage_extract": "matn ajratilmoqda",
        "summary_stage_ocr": "skan sahifalar o‘qilmoqda (OCR)",
        "summary_stage_ai": "AI tahlil qilmoqda",
        "summary_stage_finalize": "yakuniy xulosa tayyorlanmoqda",
        "summary_stage_save": "xulosa saqlanmoqda",
        "summary_stage_send": "yuborishga tayyorlanmoqda",
        "summary_stage_done": "tayyor",
        "audiobook_add_button": "➕ Audiokitob qo‘shish",
        "audiobook_add_button_with_requests": "{label} ({count})",
        "audiobook_part_saving": "⏳ Audiokitob qismi saqlanmoqda...",
        "audiobook_insert_prepare_failed": "❌ Qo‘shish o‘rni tayyorlanmadi. Qayta urinib ko‘ring.",
        "audiobook_part_save_constraint": "❌ Bu audio qismini saqlab bo‘lmadi. Qayta urinib ko‘ring.",
        "audiobook_part_save_failed": "❌ Bu audio qismini saqlab bo‘lmadi.\n{error}",
        "audiobook_listen_button": "🎧 Audiokitobni tinglash",
        "audiobook_add_intro": "🎧 Audiokitob qo‘shish rejimi.\n\nKitob uchun audio fayllarni tartib bilan yuboring (1-qism, 2-qism, ...).\nTugatgach, \"✅ Tayyor\" tugmasini bosing.",
        "audiobook_create_failed": "❌ Audiokitob yaratilmadi. Qayta urinib ko‘ring.",
        "audiobook_add_done": "✅ Audiokitob saqlandi. Qismlar soni: {count}.",
        "audiobook_part_saved": "✅ Qism #{index} saqlandi.",
        "audiobook_add_cancel": "❌ Audiokitob qo‘shish bekor qilindi.",
        "audiobook_exists_info": "🎧 Bu kitobda allaqachon {count} ta audio qism mavjud.\n\nQaysi o'ringa yangi audio qo'shmoqchisiz? (1 dan {max} gacha raqam yuboring)\nBekor qilish uchun: /cancel",
        "audiobook_insert_invalid": "❌ Noto'g'ri o'rin. 1 dan {max} gacha raqam yuboring.",
        "audiobook_insert_position_set": "✅ O'rin #{index} tanlandi. Endi audio faylni yuboring.",
        "audiobook_prev_page": "◀ Oldingi",
        "audiobook_next_page": "Keyingi ▶",
        "audiobook_page_indicator": "📄 {page}/{total} sahifa",
        "audiobook_add_not_allowed": "🚫 Sizga audiokitob qo'shishga ruxsat berilmagan.",
        "audiobook_choose_part": "🎧 Qismni tanlang:",
        "audiobook_no_parts": "❌ Bu kitob uchun audiokitob qismlari topilmadi.",
        "audiobook_missing_reply": "🎧 Bu kitob uchun audio hali qo'shilmagan.\n⏳ 1 soat ichida audio qo'shamiz.\n🔔 Xabarimizni kuting.",
        "audiobook_missing_request_query": "🎧 Audiokitob so'rovi: {title} [book_id: {book_id}]",
        "audiobook_ready_notify": "🎧 Audiokitob tayyor: {title}\n👇 Pastdagi tugmani bosib kitobni oching.",
        "audiobook_duplicate_part": "❌ Bu audio allaqachon shu kitobga qo'shilgan. Qayta qo'shish uchun avval uni o'chiring.",
        "audiobook_delete_all_button": "🗑️ Audiolarni o'chirish",
        "audiobook_delete_all_done": "✅ Shu kitobga tegishli barcha audiolar o'chirildi.",
        "audiobook_delete_all_none": "ℹ️ Bu kitob uchun o'chiriladigan audio topilmadi.",
        "summary_mode_label_short": "qisqa",
        "summary_mode_label_detailed": "batafsil",
        "summary_mode_label_points": "punktlar",
        "duplicates_title": "🧹 Dublikatlar",
        "duplicates_file_unique": "Telegram kesh (file_unique_id): guruhlar={groups}, yozuvlar={rows}, ortiqcha={extra}",
        "duplicates_path": "Lokal fayl yo‘li: guruhlar={groups}, yozuvlar={rows}, ortiqcha={extra}",
        "duplicates_name": "Nom bo‘yicha (normalize): guruhlar={groups}, yozuvlar={rows}, ortiqcha={extra}",
        "storage_title": "📦 Saqlash holati",
        "storage_total": "Jami: {total}",
        "storage_local": "Lokal fayl: {local}",
        "storage_cached": "Telegram kesh (file_id): {cached}",
        "storage_both": "Ikkalasi: {both}",
        "upload_help_prompt": "📚 Bot bazasiga kitob qo'shishni xohlaysizmi? Bu bot kutubxonasini kengaytirishga yordam beradi.",
        "answer_yes": "✅ Ha",
        "answer_no": "❌ Yo'q",
        "upload_help_sent": "✅ So'rovingiz yuborildi.",
        "upload_help_no_reply": "ℹ️ Yaxshi. Botdan foydalanishni davom ettirishingiz mumkin.",
        "upload_admin_title": "📚 Upload access request",
        "upload_admin_user": "User",
        "upload_admin_user_id": "User ID",
        "upload_admin_created": "Created",
        "upload_admin_status": "Status",
        "upload_admin_note": "Note",
        "upload_admin_updated": "Updated",
        "upload_action_accept": "✅ Accept",
        "upload_action_reject": "❌ Reject",
        "upload_admin_prompt": "✍️ Foydalanuvchiga yuborish uchun izoh yozing (holat: {status}). Bekor qilish uchun 'cancel' yozing.",
        "upload_admin_cancelled": "❌ Javob bekor qilindi.",
        "upload_reply_accept": "✅ Sizga kitob yuklashga ruxsat berildi.",
        "upload_reply_reject": "❌ Afsus, hozircha yuklashga ruxsat berilmadi.",
        "upload_reply_note": "📝 Izoh: {note}",
        "upload_status_accept": "✅ Qabul qilindi",
        "upload_status_reject": "❌ Rad etildi",
        "upload_status_updated_admin": "✅ Status yangilandi: {status}",
        "rate_limited": "⏳ Iltimos, {seconds}s kuting va qayta urinib ko'ring.",
        "spam_wait": "⏳ Juda ko‘p so‘rov. {seconds}s kuting.",
        "suggestions": "❓ Mos kelmadi. Mana shularni nazarda tutgansizmi?",
        "request_button": "📩 Kitob so‘rash",
        "request_sent": "✅ So'rovingiz yuborildi.",
        "request_usage": "📝 Kitob so‘rash bo‘limini ochib, kerakli kitob nomini yuboring.",
        "request_prompt": "✍️ Kerakli kitob nomini yuboring.",
        "request_fulfilled": "✅ Siz so'ragan kitob topildi: {title}",
        "get_book_button": "📥 Kitobni olish",
        "requests_title": "📩 So'rovlar (sahifa {page}/{pages}, jami {total})",
        "requests_empty": "📩 Sizda so'rovlar yo'q.",
        "request_status_open": "🆕 Yangi",
        "request_status_seen": "👀 Ko'rildi",
        "request_status_done": "✅ Bajarildi",
        "request_status_no": "❌ Mumkin emas",
        "request_detail": "📩 So'rov: {query}\nHolat: {status}\nYaratilgan: {created}\nYangilangan: {updated}",
        "request_status_updated": "✅ So'rovingiz yangilandi: {status}\nSo'rov: {query}",
        "request_status_updated_admin": "✅ Status yangilandi: {status}",
        "request_admin_prompt": "✍️ Foydalanuvchiga yuborish uchun izoh yozing (holat: {status}). Bekor qilish uchun 'cancel' yozing.",
        "request_admin_cancelled": "❌ So'rov javobi bekor qilindi.",
        "request_reply_open": "📩 So'rovingiz qabul qilindi: {query}",
        "request_reply_seen": "👀 So'rovingiz ko'rildi: {query}",
        "request_reply_seen_auto": "👀 So‘rovingiz tekshirilmoqda. Bu biroz vaqt olishi mumkin.",
        "request_reply_done": "✅ So'rovingiz bajarildi: {query}",
        "request_reply_no": "❌ Afsus, so'rovingizni bajarib bo'lmadi: {query}",
        "request_reply_note": "📝 Izoh: {note}",
        "request_cancel": "🗑️ So'rovni bekor qilish",
        "request_cancelled_user": "✅ So'rov bekor qilindi.",
        "request_cancelled_admin": "⚠️ Foydalanuvchi so'rovni bekor qildi. User ID: {user_id}\nSo'rov: {query}",
        "request_status_order": "⚠️ Avval 'Ko'rildi' belgilang, keyin yakunlang.",
        "request_status_already": "ℹ️ Bu so'rov allaqachon yangilangan.",
        "request_admin_title": "📩 Book request",
        "request_admin_user": "User",
        "request_admin_user_id": "User ID",
        "request_admin_query": "Query",
        "request_admin_created": "Created",
        "request_admin_status": "Status",
        "request_admin_note": "Note",
        "request_admin_updated": "Updated",
        "request_action_seen": "👀 Seen",
        "request_action_done": "✅ Done",
        "request_action_no": "❌ No",
        "request_admin_title": "📩 Book request",
        "request_admin_user": "User",
        "request_admin_user_id": "User ID",
        "request_admin_query": "Query",
        "recent_empty": "🕘 So'nggi yuklab olinganlar yo'q.",
        "recent_title": "🕘 So'nggi yuklab olinganlar:",
        "favorites_empty": "⭐ Sevimlilar bo'sh.",
        "favorites_title": "⭐ Sevimlilar:",
        "favorites_item": "• {title}",
        "favorite": "⭐ Sevimliga qo'shish",
        "unfavorite": "❌ Sevimlidan olib tashlash",
        "favorite_prompt": "⭐ Sevimlilarga qo'shishni xohlaysizmi?",
        "favorited": "⭐ Sevimlilarga qo'shildi.",
        "unfavorited": "❌ Sevimlilardan olib tashlandi.",
        "referral_joined_notice": "🎉 Yangi referal!\n👤 Ism: {name}\n🕒 Vaqt: {dt}",
        "myprofile_text": "👤 Mening profilim:\n🔎 Qidiruvlar: {searches}\n⬇️ Yuklab olishlar: {downloads}\n⭐ Sevimlilar: {favorites}\n😃 Reaksiyalar: {reactions}\n👥 Referallar: {referrals}\n📅 Aktiv kunlar: {active_days}\n📈 O'rtacha/kun: {avg_per_day}\n🗓️ Boshlangan sana: {joined}\n\n💰 Tangalar:\n🔎 Qidiruvlar: {coins_searches}\n⬇️ Yuklab olishlar: {coins_downloads}\n⭐ Sevimlilar: {coins_favorites}\n😃 Reaksiyalar: {coins_reactions}\n🔗 Referallar: {coins_referrals}\n{bonus_line}🪙 Jami: {coins_total}\n──────────\nℹ️ {ref_info}",
        "coin_bonus_line": "🎁 Bonus: {bonus}\n",
        "myprofile_ref_info": "Havolani ulashing. Yangi foydalanuvchi botni sizning havolangiz orqali ishga tushirsa, siz har bir referal uchun {coins_per_referral} tanga olasiz.",
        "share_referral_button": "🔗 Referal havolani ulashish",
        "share_referral_text": "Botdan foydalaning va kitoblarni toping.",
        "top_users_more": "Ko‘proq ko‘rsatish",
        "top_users_less": "Kamroq ko‘rsatish",
        "top_users_title": "🏆 Top foydalanuvchilar",
        "top_users_empty": "❌ Top foydalanuvchilar ro‘yxati bo‘sh.",
        "top_users_hint_more": "⬇️ Ko‘proq faol foydalanuvchilarni ko‘rish uchun “Ko‘proq ko‘rsatish”ni bosing.",
        "top_users_footer": "👤 Mening profilim bo‘limida 📊 statistika, 🎁 bonuslar va 🪙 tangalaringizni ko‘ring.\n🔗 Referal havolani ulash orqali — ko‘proq tangalarga ega bo‘ling ✨",
        "saved_indexing": "✅ Saqlandi: {file} ⏳ Indekslanmoqda",
        "saved_indexed": "✅ Saqlandi: {file} ✅ Indekslangan",
        "upload_processing": "⏳ Yuklanmoqda...",
        "sending": "⏳ Kitob yuborilmoqda...",
        "sent": "✅ Yuborildi.",
        "page_expired": "⚠️ Ushbu sahifa eskirgan. Qayta qidiring.",
        "use_buttons": "👇 Pastdagi raqamli tugmalardan birini bosing.",
        "book_next_search_hint": "😊❤️ Yana kitob kerakmi? Kitob nomini to‘g‘ridan-to‘g‘ri yuboring."
    },
    "en": {
        "greeting": (
            "Hello 👋\n"
            "{first_name}\n\n"
            "<blockquote>Welcome to the PDF and audio books bot!\n"
            "Choose one of the menus below:</blockquote>"
        ),
        "start_menu_title": "Welcome, {name} 👋",
        "start_menu_subtitle": "Choose what you want to do 👇",
        "menu_other_subtitle": "More tools and features 👇",
        "menu_search_books": "🔎 Search Books",
        "menu_text_to_voice": "🎙️ Text to Voice",
        "menu_audio_tools": "🎙️ Audio Tools",
        "menu_audio_tools_placeholder": "Choose an audio tool 👇\n🎙️ Text to Audio or 🎛️ Audio Editor.",
        "menu_audio_text_to_audio": "🎙️ Text to Audio",
        "menu_audio_converter": "🎛️ Audio Editor",
        "menu_audio_converter_placeholder": "Choose an audio editor feature 👇\n✂️ Cut audio or 🎧➡️🎙️ Change to Voice Message.",
        "menu_audio_cutter": "✂️ Cut Audio",
        "menu_audio_to_voice": "🎧➡️🎙️ Change to Voice Message",
        "menu_other_functions": "🛠️ Other Functions",
        "menu_document_tools": "📄 Document Tools",
        "menu_document_tools_placeholder": "Choose a document tool 👇\n📄 PDF Maker or 🗜️ PDF Compressor.",
        "menu_pdf_maker": "🤖 AI PDF Maker",
        "menu_pdf_editor": "🧰 PDF Editor",
        "menu_sticker_tools": "🧩 Sticker Tools",
        "menu_pdf_compressor": "🗜️ PDF Compressor",
        "menu_request_book": "📝 Request a Book",
        "menu_favorites": "⭐ Favorites",
        "menu_upload": "⬆️ Upload Books",
        "menu_contact_admin": "📞 Contact Admin",
        "menu_myprofile": "👤 My Profile",
        "menu_top_books": "🔥 Top Books",
        "menu_top_users": "🏆 Top Users",
        "menu_help": "❓ Help",
        "menu_back": "⬅️ Back",
        "menu_search_prompt": "🔎 Send the book title or author.\n\nExamples:\n<blockquote>Atomic Habits\nRich Dad Poor Dad\nThe Alchemist</blockquote>\n\n💡 For better results, send the full title or include the author.",
        "menu_search_click_first_hint": "📚 First tap `🔎 Search Books`.\nThen send the title as a normal message.",
        "menu_search_image_hint": "🖼️ I can’t read a book name from an image for search yet.\n🔎 Please send the book name as text.\n✨ An image description feature may be added later.",
        "menu_request_prompt": "📝 This section is no longer available.",
        "contact_admin_info": "📞 Contact Admin\n\nIf you have a question, suggestion, or problem, you can contact the bot owner directly.",
        "contact_admin_button": "👤 Message Admin",
        "menu_use_command_hint": "👇 Open this section from the menu below.",
        "menu_flow_cancelled": "❌ Previous process was cancelled.",
        "group_promo_short": "🌍 Join our readers community: {group}",
        "blocked": "❌ You are blocked.",
        "not_found": "❌ I couldn’t find a book for that query.\n💡 Try a more specific title or author and search again.",
        "error": "⚠️ Something went wrong.\n🔁 Please try again or reopen this section from the menu.",
        "error_notified": "⚠️ Something went wrong and the owner was notified.\n🔁 Please try again shortly.",
        "processing_general": "⏳ Processing your request...",
        "processing_search": "🔎 Searching... this takes a few seconds.",
        "admin_only": "🚫 You are not authorized to use this command.",
        "owner_only": "👑 This command is only available to the bot owner.",
        "admin_broadcast_prompt": "📣 Send the message to broadcast to all users.\nCancel: cancel",
        "admin_user_search_prompt": "👤 Send name, username, or user ID (full/partial).\nCancel: cancel",
        "bot_paused": "⏳ We’re updating the bot right now. Please wait a little. 😊❤️\n🕒 Started: {time}",
        "bot_paused_on": "⏸️ Bot paused. 🕒 {time}",
        "bot_paused_off": "▶️ Bot resumed.",
        "send_doc": "⚠️ Please send a document file.",
        "duplicate": "⚠️ Duplicate ignored:",
        "es_unavailable": "⚠️ Elasticsearch is not available, book saved locally only.",
        "saved": "✅ Saved:",
        "upload_adult_filtered": "⚠️ Book was ignored due to adult content filter:",
        "upload_file_type_filtered": "⚠️ This file type is not allowed for book uploads: {file_name}\n📚 Allowed book formats: {formats}",
        "upload_inactive": "⚠️ Upload mode is not active or you are not authorized.",
        "upload_activated": "📥 Upload mode activated. Forward me book files.",
        "not_authorized": "❌ You are not authorized to use this command.",
        "results_for": "📖 Results for",
        "results_header": "📚 {total} results found",
        "results_pick_hint": "Choose a book:",
        "results_page_line": "Page {page}/{pages}",
        "results_item_line": "{index}. {title}",
        "random_results_query": "🎲 Random books",
        "top_header": "🔥 Top books (page {page}/{pages}, total {total})",
        "top_empty": "❌ Top list is empty.",
        "choose_language": "👋 Welcome! Please choose your language:",
        "group_private_start_required": "🔐 To use the bot in this group, please start it once in private chat first.",
        "group_private_start_button": "🚀 Start Bot",
        "group_private_start_ready": "✅ Great! You have started the bot.\n🌐 Please choose your language below:",
        "group_choose_language": "🌐 Choose the language for group replies:",
        "group_search_ready": "📚 Send me the name of the book you want to search.\n↩️ Please reply to this message.",
        "book_unavailable": "❌ Book not available locally or in Telegram cache.",
        "book_unavailable_no_file": "❌ Book exists in ES but no file is available (no file_id and no local file).",
        "book_unavailable_file_missing": "❌ Local file not found. Please try again later.",
        "book_unavailable_send_failed": "❌ Failed to send the file. Please try again later.",
        "inline_book_upload_description": "Tap to upload book",
        "inline_book_info_only": "Book info only",
        "book_action_favorite": "⭐ Favorite",
        "book_action_remove_favorite": "❌ Remove",
        "book_action_rename": "✏️ Edit name",
        "book_action_delete": "🗑️ Delete book",
        "enter_specific": "⚠️ Please send a more specific book name.\n💡 Example: `Atomic Habits` or `Rich Dad Poor Dad`.",
        "book_not_found": "⚠️ Book not found.\n💡 Try a clearer full title or author name.",
        "after_book_group_invite": "📚 Join our group for new books, discussions, and useful recommendations.",
        "after_book_group_button": "🌍 Join Group",
        "audit_failed": "⚠️ Audit failed, check logs.",
        "audit_title": "📊 Audit Report",
        "audit_section_system": "🧰 System",
        "audit_section_books": "📚 Books",
        "audit_section_users": "👤 Users",
        "audit_section_requests": "📩 Requests",
        "audit_section_uploads": "⬆️ Upload requests",
        "audit_section_favorites": "⭐ Favorites",
        "audit_section_events": "🧾 Lifetime events",
        "audit_section_reactions": "💬 Reactions",
        "audit_section_today": "📅 Today",
        "audit_books_json": "Books in DB",
        "audit_books_total": "Books (total)",
        "audit_books_indexed": "Indexed",
        "audit_books_downloads_total": "Downloads (total)",
        "audit_books_searches_total": "Searches (total)",
        "audit_books_es": "Books in ES",
        "audit_unindexed": "Unindexed",
        "audit_total_users": "Total Users",
        "audit_users_blocked": "Blocked users",
        "audit_users_allowed": "Allowed users",
        "audit_joined_today": "Joined Today",
        "audit_left_today": "Left Today",
        "audit_searches_today": "Searches Today",
        "audit_buttons_today": "Books via Buttons",
        "audit_status_up": "Up",
        "audit_status_down": "Down",
        "audit_es_status": "ES status",
        "audit_es_health": "ES health",
        "audit_db_status": "DB status",
        "audit_db_error": "DB error",
        "audit_favorites_count": "Favorites count",
        "audit_favorites_total": "Favorites (total)",
        "audit_favorites_added": "Favorites added (total)",
        "audit_favorites_removed": "Favorites removed (total)",
        "audit_favorites_total": "Favorites (total)",
        "audit_favorites_added": "Favorites added (total)",
        "audit_favorites_removed": "Favorites removed (total)",
        "audit_recents_count": "Recents count",
        "audit_requests_count": "Requests count",
        "audit_requests_open": "Open",
        "audit_requests_seen": "Seen",
        "audit_requests_done": "Done",
        "audit_requests_no": "No",
        "audit_requests_open": "Open",
        "audit_requests_seen": "Seen",
        "audit_requests_done": "Done",
        "audit_requests_no": "No",
        "audit_upload_requests_count": "Upload requests count",
        "audit_upload_open": "Open",
        "audit_upload_accept": "Accepted",
        "audit_upload_reject": "Rejected",
        "audit_upload_open": "Open",
        "audit_upload_accept": "Accepted",
        "audit_upload_reject": "Rejected",
        "audit_removed_users_count": "Removed users",
        "audit_analytics_days": "Analytics days",
        "audit_unindexed_list": "❌ Unindexed books:",
        "audit_search_total": "Searches (total)",
        "audit_download_total": "Downloads (total)",
        "audit_requests_created": "Requests created (total)",
        "audit_requests_cancelled": "Requests cancelled (total)",
        "audit_requests_seen_total": "Requests seen (total)",
        "audit_requests_done_total": "Requests done (total)",
        "audit_requests_no_total": "Requests rejected (total)",
        "audit_upload_accept_total": "Uploads accepted (total)",
        "audit_upload_reject_total": "Uploads rejected (total)",
        "audit_reaction_like": "👍 Reactions (total)",
        "audit_reaction_dislike": "👎 Reactions (total)",
        "audit_reaction_berry": "🍓 Reactions (total)",
        "audit_reaction_whale": "🐳 Reactions (total)",
        "audit_reaction_current_like": "👍 Current (unique)",
        "audit_reaction_current_dislike": "👎 Current (unique)",
        "audit_reaction_current_berry": "🍓 Current (unique)",
        "audit_reaction_current_whale": "🐳 Current (unique)",
        "audit_today_joined": "Joined today",
        "audit_today_left": "Left today",
        "audit_today_searches": "Searches today",
        "audit_today_downloads": "Downloads today",
        "audit_search_total": "Searches (total)",
        "audit_download_total": "Downloads (total)",
        "audit_requests_created": "Requests created (total)",
        "audit_requests_cancelled": "Requests cancelled (total)",
        "audit_requests_seen_total": "Requests seen (total)",
        "audit_requests_done_total": "Requests done (total)",
        "audit_requests_no_total": "Requests rejected (total)",
        "audit_upload_accept_total": "Uploads accepted (total)",
        "audit_upload_reject_total": "Uploads rejected (total)",
        "audit_reaction_like": "👍 Reactions (total)",
        "audit_reaction_dislike": "👎 Reactions (total)",
        "audit_reaction_berry": "🍓 Reactions (total)",
        "audit_reaction_whale": "🐳 Reactions (total)",
        "audit_reaction_current_like": "👍 Current (unique)",
        "audit_reaction_current_dislike": "👎 Current (unique)",
        "audit_reaction_current_berry": "🍓 Current (unique)",
        "audit_reaction_current_whale": "🐳 Current (unique)",
        "broadcast_usage": "📢 Open Broadcast in Admin Control and send the message there.",
        "broadcast_done": "✅ Broadcast sent to {sent} users. Marked {blocked} blocked users.",
        "prune_started": "⏳ Prune started. I will let you know when it finishes.",
        "prune_done": "✅ Pruned {removed} blocked users. Active users left: {active}",
        "missing_title": "⚠️ Missing files:",
        "missing_none": "✅ No missing files found.",
        "missing_item": "• {title} — {reason}",
        "missing_reason_no_file_id": "no file_id",
        "missing_reason_local_missing": "local file missing",
        "missing_confirm_prompt": "⚠️ To confirm deletion, tap Missing Confirm in Admin Control within 60 seconds.",
        "missing_confirm_expired": "⏳ Confirmation expired. Open Missing Files again from Admin Control.",
        "missing_deleted": "✅ Deleted: JSON={json}, ES={es}, ES errors={es_failed}.",
        "chat_id_info": "Chat ID: {chat_id}\nType: {chat_type}\nUser ID: {user_id}",
        "delete_confirm": "⚠️ Tap delete again within 15 seconds to confirm.",
        "delete_done": "🗑️ Deleted: {title}\nDB={db}, ES={es}, ES errors={es_failed}{local}",
        "delete_local_deleted": " | local file deleted",
        "delete_local_missing": " | local file missing",
        "user_search_usage": "👤 Use Search Users in Admin Control and send a name, username, or user ID (full/partial).",
        "user_bonus_prompt_add": "➕ Add bonus for {name}.\nSend the amount (e.g. 10). Cancel: cancel",
        "user_bonus_prompt_del": "➖ Remove bonus for {name}.\nSend the amount (e.g. 5). Cancel: cancel",
        "user_bonus_invalid": "❌ Invalid amount. Send a positive number only.",
        "user_bonus_cancelled": "✅ Cancelled.",
        "user_bonus_added": "✅ Bonus added: {name} (+{amount}). New bonus: {bonus}",
        "user_bonus_removed": "✅ Bonus removed: {name} (-{amount}). New bonus: {bonus}",
        "bonus_received_notice": "🎉 Congratulations! You received {amount} bonus coins.\n👤 You can view your stats, 🪙 coins, and 🎁 bonuses in the My Profile section.",
        "user_search_empty": "❌ No users found.",
        "user_search_title": "👤 Results for '{query}'",
        "user_results_header": "👤 User results: {total}",
        "user_results_pick_hint": "Choose a user:",
        "user_not_found": "❌ User not found.",
        "stop_disabled_notice": "✅ You can use the bot again. Choose a section from the menu below.",
        "upload_allowed_notice": "✅ You are now allowed to upload books.",
        "delete_allowed_notice": "✅ You are now allowed to delete books.",
        "audio_allowed_notice": "✅ You are now allowed to add audiobooks.",
        "book_rename_private_only": "✏️ Book renaming is available only in private chat.",
        "help_text": "📚 Help\nUse the menu below for the fastest experience.\n──────────\n🔎 Search Books — find books by title or author.\n🎙️ Text to Voice — turn text into audio.\n👤 My Profile — check your stats and coins.\n🛠️ Other Functions — PDF tools, top lists, favorites, uploads, and more.\n──────────\n🌐 To change language, open `Language`.",
        "thanks_reply": "You're welcome! Happy reading 🍓",
        "summary_coming_soon": "🧠 AI book summarizer is coming soon.",
        "summary_button": "🧠 Summarize",
        "summary_choose_mode": "🧠 Choose summary type:",
        "summary_mode_short": "Short",
        "summary_mode_detailed": "Detailed",
        "summary_mode_points": "Key points",
        "summary_mode_cancel": "Cancel",
        "summary_working": "⏳ Preparing book summary...",
        "summary_ready_title": "🧠 Book summary ({mode})",
        "summary_cached_note": "⚡ Cached summary",
        "summary_already_running": "⏳ A summary for this book is already being prepared.",
        "summary_book_missing": "❌ Book not found.",
        "summary_no_source": "❌ No file source found for this book.",
        "summary_download_failed": "❌ Failed to download file for summarization.",
        "summary_download_too_big": "❌ File is too large for Telegram bot download. A local copy (path) is required.",
        "summary_extract_failed": "❌ Failed to extract text. This file type may not be supported.",
        "summary_empty_text": "❌ No readable text found in the file (it may be a scanned PDF).",
        "summary_ai_unavailable": "⚠️ AI summarizer is unavailable right now. Please try again later.",
        "summary_error": "⚠️ Failed to prepare summary.",
        "summary_progress_prefix": "🧠 Preparing summary",
        "summary_progress_elapsed": "⏱️ {seconds}s",
        "summary_stage_start": "starting",
        "summary_stage_cache": "checking cache",
        "summary_stage_source": "checking file source",
        "summary_stage_download": "downloading file",
        "summary_stage_extract": "extracting text",
        "summary_stage_ocr": "scanning pages (OCR)",
        "summary_stage_ai": "analyzing with AI",
        "summary_stage_finalize": "building final summary",
        "summary_stage_save": "saving summary",
        "summary_stage_send": "preparing to send",
        "summary_stage_done": "done",
        "audiobook_add_button": "➕ Add Audiobook",
        "audiobook_add_button_with_requests": "{label} ({count})",
        "audiobook_part_saving": "⏳ Saving audiobook part...",
        "audiobook_part_saved": "✅ Part #{index} saved.",
        "audiobook_insert_prepare_failed": "❌ Couldn't prepare the insert position. Please try again.",
        "audiobook_part_save_constraint": "❌ Couldn't save this audio part. Please try again.",
        "audiobook_part_save_failed": "❌ Couldn't save this audio part.\n{error}",
        "audiobook_listen_button": "🎧 Listen Audiobook",
        "audiobook_add_intro": "🎧 Audiobook upload mode.\n\nSend audio files for this book in order (Part 1, Part 2, ...).\nWhen finished, tap \"✅ Done\".",
        "audiobook_create_failed": "❌ Failed to create audiobook. Please try again.",
        "audiobook_add_done": "✅ Audiobook saved. Parts: {count}.",
        "audiobook_add_cancel": "❌ Audiobook upload cancelled.",
        "audiobook_exists_info": "🎧 This book already has {count} audio part(s).\n\nAt which position do you want to insert the new audio? (Send a number from 1 to {max})\nTo cancel: /cancel",
        "audiobook_insert_invalid": "❌ Invalid position. Send a number from 1 to {max}.",
        "audiobook_insert_position_set": "✅ Position #{index} selected. Now send the audio file.",
        "audiobook_prev_page": "◀ Prev",
        "audiobook_next_page": "Next ▶",
        "audiobook_page_indicator": "📄 Page {page}/{total}",
        "audiobook_add_not_allowed": "🚫 You are not allowed to add audiobooks.",
        "audiobook_choose_part": "🎧 Choose a part to play:",
        "audiobook_no_parts": "❌ No audiobook parts found for this book.",
        "audiobook_missing_reply": "🎧 This book has no audiobook yet.\n⏳ We will add it within 1 hour.\n🔔 Wait for our message.",
        "audiobook_missing_request_query": "🎧 Audiobook request: {title} [book_id: {book_id}]",
        "audiobook_ready_notify": "🎧 Audiobook is ready: {title}\n👇 Tap the button below to open the book.",
        "audiobook_duplicate_part": "❌ This audio is already added to this book. Delete it first if you want to re-add it.",
        "audiobook_delete_all_button": "🗑️ Delete Audios",
        "audiobook_delete_all_done": "✅ All audios for this book were deleted.",
        "audiobook_delete_all_none": "ℹ️ This book has no audios to delete.",
        "summary_mode_label_short": "short",
        "summary_mode_label_detailed": "detailed",
        "summary_mode_label_points": "key points",
        "duplicates_title": "🧹 Duplicates",
        "duplicates_file_unique": "Telegram cache (file_unique_id): groups={groups}, rows={rows}, extra={extra}",
        "duplicates_path": "Local path: groups={groups}, rows={rows}, extra={extra}",
        "duplicates_name": "Name (normalized): groups={groups}, rows={rows}, extra={extra}",
        "storage_title": "📦 Storage",
        "storage_total": "Total: {total}",
        "storage_local": "Local files: {local}",
        "storage_cached": "Telegram cache (file_id): {cached}",
        "storage_both": "Both: {both}",
        "upload_help_prompt": "📚 Do you want to add books to the bot database and help expand the library?",
        "answer_yes": "✅ Yes",
        "answer_no": "❌ No",
        "upload_help_sent": "✅ Your request has been sent.",
        "upload_help_no_reply": "ℹ️ No problem. You can continue using the bot.",
        "upload_admin_title": "📚 Upload access request",
        "upload_admin_user": "User",
        "upload_admin_user_id": "User ID",
        "upload_admin_created": "Created",
        "upload_admin_status": "Status",
        "upload_admin_note": "Note",
        "upload_admin_updated": "Updated",
        "upload_action_accept": "✅ Accept",
        "upload_action_reject": "❌ Reject",
        "upload_admin_prompt": "✍️ Please type a message for the user (status: {status}). Send 'cancel' to abort.",
        "upload_admin_cancelled": "❌ Reply cancelled.",
        "upload_reply_accept": "✅ You are allowed to upload books now.",
        "upload_reply_reject": "❌ Sorry, upload access is not granted at this time.",
        "upload_reply_note": "📝 Note: {note}",
        "upload_status_accept": "✅ Accepted",
        "upload_status_reject": "❌ Rejected",
        "upload_status_updated_admin": "✅ Status updated: {status}",
        "rate_limited": "⏳ Please wait {seconds}s and try again.",
        "spam_wait": "⏳ Too many requests. Please wait {seconds}s.",
        "suggestions": "❓ No exact match. Did you mean one of these?",
        "request_button": "📩 Request a book",
        "request_sent": "✅ Your request has been sent.",
        "request_usage": "📝 Open Request a Book in the menu and send the book name you need.",
        "request_prompt": "✍️ Please send the book name you want.",
        "request_fulfilled": "✅ Your requested book is now available: {title}",
        "get_book_button": "📥 Get book",
        "requests_title": "📩 Requests (page {page}/{pages}, total {total})",
        "requests_empty": "📩 You have no requests.",
        "request_status_open": "🆕 Open",
        "request_status_seen": "👀 Seen",
        "request_status_done": "✅ Done",
        "request_status_no": "❌ Not possible",
        "request_detail": "📩 Request: {query}\nStatus: {status}\nCreated: {created}\nUpdated: {updated}",
        "request_status_updated": "✅ Your request was updated: {status}\nRequest: {query}",
        "request_status_updated_admin": "✅ Status updated: {status}",
        "request_admin_prompt": "✍️ Please type a message for the user (status: {status}). Send 'cancel' to abort.",
        "request_admin_cancelled": "❌ Request reply cancelled.",
        "request_reply_open": "📩 Your request was received: {query}",
        "request_reply_seen": "👀 Your request was seen: {query}",
        "request_reply_seen_auto": "👀 Your request is being checked. This may take some time.",
        "request_reply_done": "✅ Your request was completed: {query}",
        "request_reply_no": "❌ Sorry, your request can’t be fulfilled: {query}",
        "request_reply_note": "📝 Note: {note}",
        "request_cancel": "🗑️ Cancel request",
        "request_cancelled_user": "✅ Your request was cancelled.",
        "request_cancelled_admin": "⚠️ User cancelled the request. User ID: {user_id}\nRequest: {query}",
        "request_status_order": "⚠️ Please mark as Seen first before Done/No.",
        "request_status_already": "ℹ️ This request is already updated.",
        "request_admin_title": "📩 Book request",
        "request_admin_user": "User",
        "request_admin_user_id": "User ID",
        "request_admin_query": "Query",
        "request_admin_created": "Created",
        "request_admin_status": "Status",
        "request_admin_note": "Note",
        "request_admin_updated": "Updated",
        "request_action_seen": "👀 Seen",
        "request_action_done": "✅ Done",
        "request_action_no": "❌ No",
        "request_admin_title": "📩 Book request",
        "request_admin_user": "User",
        "request_admin_user_id": "User ID",
        "request_admin_query": "Query",
        "recent_empty": "🕘 No recent downloads.",
        "recent_title": "🕘 Recent downloads:",
        "favorites_empty": "⭐ Favorites list is empty.",
        "favorites_title": "⭐ Favorites:",
        "favorites_item": "• {title}",
        "favorite": "⭐ Add to favorites",
        "unfavorite": "❌ Remove from favorites",
        "favorite_prompt": "⭐ Add this book to favorites?",
        "favorited": "⭐ Added to favorites.",
        "unfavorited": "❌ Removed from favorites.",
        "referral_joined_notice": "🎉 New referral!\n👤 Name: {name}\n🕒 Time: {dt}",
        "myprofile_text": "👤 My profile:\n🔎 Searches: {searches}\n⬇️ Downloads: {downloads}\n⭐ Favorites: {favorites}\n😃 Reactions: {reactions}\n👥 Referrals: {referrals}\n📅 Active days: {active_days}\n📈 Avg/day: {avg_per_day}\n🗓️ Joined: {joined}\n\n💰 Coins:\n🔎 Searches: {coins_searches}\n⬇️ Downloads: {coins_downloads}\n⭐ Favorites: {coins_favorites}\n😃 Reactions: {coins_reactions}\n🔗 Referrals: {coins_referrals}\n{bonus_line}🪙 Total: {coins_total}\n──────────\nℹ️ {ref_info}",
        "coin_bonus_line": "🎁 Bonus: {bonus}\n",
        "myprofile_ref_info": "Share your link. When a new user starts the bot using it, you earn {coins_per_referral} coins per referral.",
        "share_referral_button": "🔗 Share referral link",
        "share_referral_text": "Use this bot to find books.",
        "top_users_more": "Show more",
        "top_users_less": "Show less",
        "top_users_title": "🏆 Top users",
        "top_users_empty": "❌ Top users list is empty.",
        "top_users_hint_more": "⬇️ Tap “Show more” to see more active users.",
        "top_users_footer": "👤 Open My Profile to see your 📊 stats and 🪙 coins.\n🔗 Share your referral link there too.\n✨ Invite your friend via referral link and get more coins.",
        "saved_indexing": "✅ Saved: {file} ⏳ Indexing",
        "saved_indexed": "✅ Saved: {file} ✅ Indexed",
        "upload_processing": "⏳ Processing your upload...",
        "sending": "⏳ Sending book...",
        "sent": "✅ Sent.",
        "book_next_search_hint": "😊❤️ Want another book? Just send the book name directly.",
        "page_expired": "⚠️ This page expired. Please search again.",
        "use_buttons": "👇 Tap one of the numbered buttons below."
    },
    "ru": {
        "greeting": (
            "Здравствуйте 👋\n"
            "{first_name}\n\n"
            "<blockquote>Добро пожаловать в бот PDF и аудиокниг!\n"
            "Выберите одно из меню ниже:</blockquote>"
        ),
        "start_menu_title": "Здравствуйте, {name} 👋",
        "start_menu_subtitle": "Выберите нужный раздел 👇",
        "menu_other_subtitle": "Дополнительные инструменты 👇",
        "menu_search_books": "🔎 Поиск книг",
        "menu_text_to_voice": "🎙️ Текст в голос",
        "menu_audio_tools": "🎙️ Аудио инструменты",
        "menu_audio_tools_placeholder": "Выберите аудио-инструмент 👇\n🎙️ Text to Audio или 🎛️ Аудиоредактор.",
        "menu_audio_text_to_audio": "🎙️ Text to Audio",
        "menu_audio_converter": "🎛️ Аудиоредактор",
        "menu_audio_converter_placeholder": "Выберите функцию аудиоредактора 👇\n✂️ Обрезать или 🎧➡️🎙️ В voice сообщение.",
        "menu_audio_cutter": "✂️ Обрезать аудио",
        "menu_audio_to_voice": "🎧➡️🎙️ В voice сообщение",
        "menu_other_functions": "🛠️ Другие функции",
        "menu_document_tools": "📄 Инструменты документов",
        "menu_document_tools_placeholder": "Выберите инструмент документов 👇\n📄 PDF Maker или 🗜️ PDF Compressor.",
        "menu_pdf_maker": "🤖 AI PDF Maker",
        "menu_pdf_editor": "🧰 PDF редактор",
        "menu_sticker_tools": "🧩 Стикер инструменты",
        "menu_pdf_compressor": "🗜️ PDF Compressor",
        "menu_request_book": "📝 Запрос книги",
        "menu_favorites": "⭐ Избранное",
        "menu_upload": "⬆️ Загрузить книги",
        "menu_contact_admin": "📞 Связаться с админом",
        "menu_myprofile": "👤 Мой профиль",
        "menu_top_books": "🔥 Топ книг",
        "menu_top_users": "🏆 Топ пользователей",
        "menu_help": "❓ Помощь",
        "menu_back": "⬅️ Назад",
        "menu_search_prompt": "🔎 Отправьте название книги или автора.\n\nНапример:\n<blockquote>Atomic Habits\nШайтанат\nАлхимик</blockquote>\n\n💡 Для более точного результата отправляйте полное название или автора.",
        "menu_search_click_first_hint": "📚 Сначала нажмите `🔎 Поиск книг`.\nЗатем отправьте название обычным сообщением.",
        "menu_search_image_hint": "🖼️ Пока я не умею читать название книги с изображения для поиска.\n🔎 Пожалуйста, отправьте название книги текстом.\n✨ Позже может быть добавлена функция описания изображения.",
        "menu_request_prompt": "📝 Этот раздел больше недоступен.",
        "contact_admin_info": "📞 Связь с админом\n\nЕсли у вас есть вопрос, предложение или проблема, вы можете написать владельцу бота напрямую.",
        "contact_admin_button": "👤 Написать админу",
        "menu_use_command_hint": "👇 Откройте этот раздел через меню ниже.",
        "menu_flow_cancelled": "❌ Предыдущий процесс отменён.",
        "group_promo_short": "🌍 Присоединяйтесь к нашему сообществу читателей: {group}",
        "blocked": "❌ Вы заблокированы.",
        "not_found": "❌ Книга по этому запросу не найдена.\n💡 Уточните название или автора и попробуйте снова.",
        "error": "⚠️ Произошла непредвиденная ошибка.\n🔁 Попробуйте ещё раз или заново откройте раздел через меню.",
        "error_notified": "⚠️ Произошла ошибка, владелец уведомлён.\n🔁 Пожалуйста, попробуйте снова чуть позже.",
        "processing_general": "⏳ Обрабатываю ваш запрос...",
        "processing_search": "🔎 Ищу... это займёт несколько секунд.",
        "admin_only": "🚫 У вас нет прав для этой команды.",
        "owner_only": "👑 Эта команда доступна только владельцу бота.",
        "admin_broadcast_prompt": "📣 Отправьте сообщение для рассылки всем пользователям.\nОтмена: cancel",
        "admin_user_search_prompt": "👤 Отправьте имя, username или user ID (полностью/частично).\nОтмена: cancel",
        "bot_paused": "⏳ Сейчас идут обновления бота. Пожалуйста, подождите немного. 😊❤️\n🕒 Начало: {time}",
        "bot_paused_on": "⏸️ Бот поставлен на паузу. 🕒 {time}",
        "bot_paused_off": "▶️ Бот снова работает.",
        "send_doc": "⚠️ Пожалуйста, отправьте файл документа.",
        "duplicate": "⚠️ Дубликат проигнорирован:",
        "es_unavailable": "⚠️ Elasticsearch недоступен, книга сохранена только локально.",
        "saved": "✅ Сохранено:",
        "upload_adult_filtered": "⚠️ Книга проигнорирована фильтром контента 18+:",
        "upload_file_type_filtered": "⚠️ Этот тип файла не подходит для загрузки книг: {file_name}\n📚 Разрешённые форматы книг: {formats}",
        "upload_inactive": "⚠️ Режим загрузки не активен или у вас нет доступа.",
        "upload_activated": "📥 Режим загрузки активирован. Перешлите мне файлы книг.",
        "not_authorized": "❌ У вас нет прав для использования этой команды.",
        "results_for": "📖 Результаты",
        "results_header": "📚 Найдено результатов: {total}",
        "results_pick_hint": "Выберите книгу:",
        "results_page_line": "Страница {page}/{pages}",
        "results_item_line": "{index}. {title}",
        "random_results_query": "🎲 Случайные книги",
        "top_header": "🔥 Топ книг (страница {page}/{pages}, всего {total})",
        "top_empty": "❌ Топ список пуст.",
        "choose_language": "👋 Добро пожаловать! Выберите язык:",
        "group_private_start_required": "🔐 Чтобы пользоваться ботом в группе, сначала один раз запустите его в личном чате.",
        "group_private_start_button": "🚀 Открыть бота",
        "group_private_start_ready": "✅ Отлично! Вы запустили бота.\n🌐 Теперь выберите язык:",
        "group_choose_language": "🌐 Выберите язык для ответов в группе:",
        "group_search_ready": "📚 Отправьте название книги, которую хотите найти.\n↩️ Пожалуйста, ответьте на это сообщение.",
        "book_unavailable": "❌ Книга недоступна (локально или в кэше).",
        "book_unavailable_no_file": "❌ Книга есть в ES, но файл недоступен (нет file_id и локального файла).",
        "book_unavailable_file_missing": "❌ Локальный файл не найден. Попробуйте позже.",
        "book_unavailable_send_failed": "❌ Не удалось отправить файл. Попробуйте позже.",
        "inline_book_upload_description": "Нажмите, чтобы отправить книгу",
        "inline_book_info_only": "Только информация о книге",
        "book_action_favorite": "⭐ В избранное",
        "book_action_remove_favorite": "❌ Убрать",
        "book_action_rename": "✏️ Переименовать",
        "book_action_delete": "🗑️ Удалить книгу",
        "enter_specific": "⚠️ Отправьте более точное название книги.\n💡 Например: `Atomic Habits` или `Шайтанат 1`.",
        "book_not_found": "⚠️ Книга не найдена.\n💡 Попробуйте более точное полное название или автора.",
        "after_book_group_invite": "📚 Вступайте в нашу группу: новые книги, обсуждения и полезные рекомендации.",
        "after_book_group_button": "🌍 Вступить в группу",
        "audit_failed": "⚠️ Аудит не выполнен, проверьте логи.",
        "audit_title": "📊 Отчет аудита",
        "audit_section_system": "🧰 Система",
        "audit_section_books": "📚 Книги",
        "audit_section_users": "👤 Пользователи",
        "audit_section_requests": "📩 Запросы",
        "audit_section_uploads": "⬆️ Upload запросы",
        "audit_section_favorites": "⭐ Избранное",
        "audit_section_events": "🧾 События (всего)",
        "audit_section_reactions": "💬 Реакции",
        "audit_section_today": "📅 Сегодня",
        "audit_books_json": "Книг в БД",
        "audit_books_total": "Книги (всего)",
        "audit_books_indexed": "Индексированы",
        "audit_books_downloads_total": "Скачивания (всего)",
        "audit_books_searches_total": "Поиски (всего)",
        "audit_books_es": "Книг в ES",
        "audit_unindexed": "Неиндексированные",
        "audit_total_users": "Всего пользователей",
        "audit_users_blocked": "Заблокированные пользователи",
        "audit_users_allowed": "Разрешенные пользователи",
        "audit_joined_today": "Присоединились сегодня",
        "audit_left_today": "Ушли сегодня",
        "audit_searches_today": "Поиски сегодня",
        "audit_buttons_today": "Книги через кнопки",
        "audit_status_up": "Работает",
        "audit_status_down": "Не работает",
        "audit_es_status": "Статус ES",
        "audit_es_health": "ES health",
        "audit_db_status": "Статус БД",
        "audit_db_error": "Ошибка БД",
        "audit_favorites_count": "Избранных",
        "audit_favorites_total": "Избранное (всего)",
        "audit_favorites_added": "Добавлено в избранное (всего)",
        "audit_favorites_removed": "Удалено из избранного (всего)",
        "audit_recents_count": "Недавние",
        "audit_requests_count": "Запросов",
        "audit_requests_open": "Новые",
        "audit_requests_seen": "Просмотрено",
        "audit_requests_done": "Выполнено",
        "audit_requests_no": "Невозможно",
        "audit_upload_requests_count": "Запросы на загрузку",
        "audit_upload_open": "Новые",
        "audit_upload_accept": "Принятые",
        "audit_upload_reject": "Отклоненные",
        "audit_removed_users_count": "Удаленные пользователи",
        "audit_analytics_days": "Дни аналитики",
        "audit_unindexed_list": "❌ Неиндексированные книги:",
        "audit_search_total": "Поиски (всего)",
        "audit_download_total": "Скачивания (всего)",
        "audit_requests_created": "Запросы созданы (всего)",
        "audit_requests_cancelled": "Запросы отменены (всего)",
        "audit_requests_seen_total": "Запросы просмотрены (всего)",
        "audit_requests_done_total": "Запросы выполнены (всего)",
        "audit_requests_no_total": "Запросы отклонены (всего)",
        "audit_upload_accept_total": "Upload принят (всего)",
        "audit_upload_reject_total": "Upload отклонен (всего)",
        "audit_reaction_like": "👍 Реакции (всего)",
        "audit_reaction_dislike": "👎 Реакции (всего)",
        "audit_reaction_berry": "🍓 Реакции (всего)",
        "audit_reaction_whale": "🐳 Реакции (всего)",
        "audit_reaction_current_like": "👍 Текущие (уник.)",
        "audit_reaction_current_dislike": "👎 Текущие (уник.)",
        "audit_reaction_current_berry": "🍓 Текущие (уник.)",
        "audit_reaction_current_whale": "🐳 Текущие (уник.)",
        "audit_today_joined": "Присоединились сегодня",
        "audit_today_left": "Ушли сегодня",
        "audit_today_searches": "Поиски сегодня",
        "audit_today_downloads": "Скачивания сегодня",
        "broadcast_usage": "📢 Откройте Broadcast в Admin Control и отправьте там сообщение.",
        "broadcast_done": "✅ Рассылка отправлена {sent} пользователям. Отмечено {blocked} заблокированных.",
        "prune_started": "⏳ Очистка запущена. Сообщу, когда завершится.",
        "prune_done": "✅ Удалено {removed} заблокированных. Активных осталось: {active}",
        "missing_title": "⚠️ Отсутствующие файлы:",
        "missing_none": "✅ Отсутствующие файлы не найдены.",
        "missing_item": "• {title} — {reason}",
        "missing_reason_no_file_id": "нет file_id",
        "missing_reason_local_missing": "локальный файл отсутствует",
        "missing_confirm_prompt": "⚠️ Для подтверждения удаления нажмите Missing Confirm в Admin Control в течение 60 секунд.",
        "missing_confirm_expired": "⏳ Время подтверждения истекло. Снова откройте Missing Files в Admin Control.",
        "missing_deleted": "✅ Удалено: JSON={json}, ES={es}, Ошибки ES={es_failed}.",
        "chat_id_info": "Chat ID: {chat_id}\nТип: {chat_type}\nUser ID: {user_id}",
        "delete_confirm": "⚠️ Нажмите удалить ещё раз в течение 15 секунд для подтверждения.",
        "delete_done": "🗑️ Удалено: {title}\nDB={db}, ES={es}, Ошибки ES={es_failed}{local}",
        "delete_local_deleted": " | локальный файл удалён",
        "delete_local_missing": " | локальный файл не найден",
        "user_search_usage": "👤 Используйте Search Users в Admin Control и отправьте имя, username или user ID (полностью/частично).",
        "user_bonus_prompt_add": "➕ Добавить бонус для {name}.\nОтправьте сумму (например: 10). Отмена: cancel",
        "user_bonus_prompt_del": "➖ Уменьшить бонус для {name}.\nОтправьте сумму (например: 5). Отмена: cancel",
        "user_bonus_invalid": "❌ Неверная сумма. Отправьте только положительное число.",
        "user_bonus_cancelled": "✅ Отменено.",
        "user_bonus_added": "✅ Бонус добавлен: {name} (+{amount}). Новый бонус: {bonus}",
        "user_bonus_removed": "✅ Бонус уменьшен: {name} (-{amount}). Новый бонус: {bonus}",
        "bonus_received_notice": "🎉 Поздравляем! Вы получили {amount} бонусных монет.\n👤 В разделе «Мой профиль» вы можете посмотреть свою статистику, 🪙 монеты и 🎁 бонусы.",
        "user_search_empty": "❌ Пользователи не найдены.",
        "user_search_title": "👤 Результаты для '{query}'",
        "user_results_header": "👤 Результаты пользователей: {total}",
        "user_results_pick_hint": "Выберите пользователя:",
        "user_not_found": "❌ Пользователь не найден.",
        "stop_disabled_notice": "✅ Вы снова можете пользоваться ботом. Выберите раздел в меню ниже.",
        "upload_allowed_notice": "✅ Вам разрешено загружать книги.",
        "delete_allowed_notice": "✅ Вам разрешено удалять книги.",
        "audio_allowed_notice": "✅ Вам разрешено добавлять аудиокниги.",
        "book_rename_private_only": "✏️ Переименование книги доступно только в личном чате.",
        "help_text": "📚 Помощь\nДля удобства используйте разделы в меню ниже.\n──────────\n🔎 Поиск книг — поиск по названию или автору.\n🎙️ Текст в голос — преобразование текста в аудио.\n👤 Мой профиль — ваша статистика и монеты.\n🛠️ Другие функции — PDF-инструменты, топы, избранное, запросы и загрузка.\n──────────\n🌐 Сменить язык можно в разделе `Language`.",
        "thanks_reply": "Пожалуйста 🍓",
        "summary_coming_soon": "🧠 AI-суммаризация книги скоро будет добавлена.",
        "summary_button": "🧠 Кратко",
        "summary_choose_mode": "🧠 Выберите тип краткого содержания:",
        "summary_mode_short": "Коротко",
        "summary_mode_detailed": "Подробно",
        "summary_mode_points": "Пункты",
        "summary_mode_cancel": "Отмена",
        "summary_working": "⏳ Подготавливаю краткое содержание книги...",
        "summary_ready_title": "🧠 Краткое содержание ({mode})",
        "summary_cached_note": "⚡ Сохранённая версия",
        "summary_already_running": "⏳ Краткое содержание для этой книги уже готовится.",
        "summary_book_missing": "❌ Книга не найдена.",
        "summary_no_source": "❌ Источник файла для этой книги не найден.",
        "summary_download_failed": "❌ Не удалось скачать файл для суммаризации.",
        "summary_download_too_big": "❌ Файл слишком большой для загрузки через Bot API. Нужна локальная копия (path).",
        "summary_extract_failed": "❌ Не удалось извлечь текст. Возможно, этот тип файла не поддерживается.",
        "summary_empty_text": "❌ В файле не найден читаемый текст (возможно, это скан PDF).",
        "summary_ai_unavailable": "⚠️ AI-суммаризатор сейчас недоступен. Попробуйте позже.",
        "summary_error": "⚠️ Не удалось подготовить краткое содержание.",
        "summary_progress_prefix": "🧠 Готовлю краткое содержание",
        "summary_progress_elapsed": "⏱️ {seconds}с",
        "summary_stage_start": "запуск",
        "summary_stage_cache": "проверка кэша",
        "summary_stage_source": "проверка источника файла",
        "summary_stage_download": "загрузка файла",
        "summary_stage_extract": "извлечение текста",
        "summary_stage_ocr": "распознавание страниц (OCR)",
        "summary_stage_ai": "анализ через AI",
        "summary_stage_finalize": "сборка итогового содержания",
        "summary_stage_save": "сохранение содержания",
        "summary_stage_send": "подготовка к отправке",
        "summary_stage_done": "готово",
        "audiobook_add_button": "➕ Добавить аудиокнигу",
        "audiobook_add_button_with_requests": "{label} ({count})",
        "audiobook_part_saving": "⏳ Сохранение аудиочасти...",
        "audiobook_part_saved": "✅ Часть №{index} сохранена.",
        "audiobook_insert_prepare_failed": "❌ Не удалось подготовить позицию вставки. Попробуйте ещё раз.",
        "audiobook_part_save_constraint": "❌ Не удалось сохранить эту аудиочасть. Попробуйте ещё раз.",
        "audiobook_part_save_failed": "❌ Не удалось сохранить эту аудиочасть.\n{error}",
        "audiobook_listen_button": "🎧 Слушать аудиокнигу",
        "audiobook_add_intro": "🎧 Режим добавления аудиокниги.\n\nОтправляйте аудиофайлы для этой книги по порядку (Часть 1, Часть 2, ...).\nКогда закончите, нажмите \"✅ Готово\".",
        "audiobook_create_failed": "❌ Не удалось создать аудиокнигу. Попробуйте ещё раз.",
        "audiobook_add_done": "✅ Аудиокнига сохранена. Кол-во частей: {count}.",
        "audiobook_add_cancel": "❌ Добавление аудиокниги отменено.",
        "audiobook_exists_info": "🎧 У этой книги уже есть {count} аудиочасть(ей).\n\nНа какую позицию вставить новое аудио? (Отправьте число от 1 до {max})\nДля отмены: /cancel",
        "audiobook_insert_invalid": "❌ Неверная позиция. Отправьте число от 1 до {max}.",
        "audiobook_insert_position_set": "✅ Позиция #{index} выбрана. Теперь отправьте аудиофайл.",
        "audiobook_prev_page": "◀ Назад",
        "audiobook_next_page": "Далее ▶",
        "audiobook_page_indicator": "📄 Стр. {page}/{total}",
        "audiobook_add_not_allowed": "🚫 У вас нет прав для добавления аудиокниг.",
        "audiobook_choose_part": "🎧 Выберите часть:",
        "audiobook_no_parts": "❌ Для этой книги аудиочасти не найдены.",
        "audiobook_missing_reply": "🎧 Для этой книги пока нет аудио.\n⏳ Мы добавим аудио в течение 1 часа.\n🔔 Дождитесь нашего сообщения.",
        "audiobook_missing_request_query": "🎧 Запрос аудиокниги: {title} [book_id: {book_id}]",
        "audiobook_ready_notify": "🎧 Аудиокнига готова: {title}\n👇 Нажмите кнопку ниже, чтобы открыть книгу.",
        "audiobook_duplicate_part": "❌ Это аудио уже добавлено в эту книгу. Сначала удалите его, если хотите добавить заново.",
        "audiobook_delete_all_button": "🗑️ Удалить аудио",
        "audiobook_delete_all_done": "✅ Все аудио этой книги удалены.",
        "audiobook_delete_all_none": "ℹ️ Для этой книги нет аудио для удаления.",
        "summary_mode_label_short": "коротко",
        "summary_mode_label_detailed": "подробно",
        "summary_mode_label_points": "пункты",
        "duplicates_title": "🧹 Дубликаты",
        "duplicates_file_unique": "Кеш Telegram (file_unique_id): групп={groups}, записей={rows}, лишних={extra}",
        "duplicates_path": "Локальный путь: групп={groups}, записей={rows}, лишних={extra}",
        "duplicates_name": "По названию (normalize): групп={groups}, записей={rows}, лишних={extra}",
        "storage_title": "📦 Хранение",
        "storage_total": "Всего: {total}",
        "storage_local": "Локальные файлы: {local}",
        "storage_cached": "Кеш Telegram (file_id): {cached}",
        "storage_both": "Оба: {both}",
        "upload_help_prompt": "📚 Хотите добавлять книги в базу и помогать расширять библиотеку?",
        "answer_yes": "✅ Да",
        "answer_no": "❌ Нет",
        "upload_help_sent": "✅ Ваш запрос отправлен.",
        "upload_help_no_reply": "ℹ️ Хорошо. Можете продолжать пользоваться ботом.",
        "upload_admin_title": "📚 Upload access request",
        "upload_admin_user": "User",
        "upload_admin_user_id": "User ID",
        "upload_admin_created": "Created",
        "upload_admin_status": "Status",
        "upload_admin_note": "Note",
        "upload_admin_updated": "Updated",
        "upload_action_accept": "✅ Accept",
        "upload_action_reject": "❌ Reject",
        "upload_admin_prompt": "✍️ Напишите сообщение пользователю (статус: {status}). Для отмены отправьте 'cancel'.",
        "upload_admin_cancelled": "❌ Ответ отменён.",
        "upload_reply_accept": "✅ Вам разрешено загружать книги.",
        "upload_reply_reject": "❌ Извините, доступ к загрузке пока не предоставлен.",
        "upload_reply_note": "📝 Сообщение: {note}",
        "upload_status_accept": "✅ Принято",
        "upload_status_reject": "❌ Отклонено",
        "upload_status_updated_admin": "✅ Статус обновлён: {status}",
        "rate_limited": "⏳ Пожалуйста, подождите {seconds}с и попробуйте снова.",
        "spam_wait": "⏳ Слишком много запросов. Подождите {seconds}с.",
        "suggestions": "❓ Точного совпадения нет. Возможно, вы имели в виду одно из этих?",
        "request_button": "📩 Запросить книгу",
        "request_sent": "✅ Ваш запрос отправлен.",
        "request_usage": "📝 Откройте раздел запроса книги в меню и отправьте нужное название.",
        "request_prompt": "✍️ Отправьте название нужной книги.",
        "request_fulfilled": "✅ Запрошенная книга найдена: {title}",
        "get_book_button": "📥 Получить книгу",
        "requests_title": "📩 Запросы (страница {page}/{pages}, всего {total})",
        "requests_empty": "📩 У вас нет запросов.",
        "request_status_open": "🆕 Новый",
        "request_status_seen": "👀 Просмотрено",
        "request_status_done": "✅ Выполнено",
        "request_status_no": "❌ Невозможно",
        "request_detail": "📩 Запрос: {query}\nСтатус: {status}\nСоздан: {created}\nОбновлён: {updated}",
        "request_status_updated": "✅ Ваш запрос обновлён: {status}\nЗапрос: {query}",
        "request_status_updated_admin": "✅ Статус обновлён: {status}",
        "request_admin_prompt": "✍️ Напишите сообщение пользователю (статус: {status}). Для отмены отправьте 'cancel'.",
        "request_admin_cancelled": "❌ Ответ на запрос отменён.",
        "request_reply_open": "📩 Ваш запрос получен: {query}",
        "request_reply_seen": "👀 Ваш запрос просмотрен: {query}",
        "request_reply_seen_auto": "👀 Ваш запрос проверяется. Это может занять немного времени.",
        "request_reply_done": "✅ Ваш запрос выполнен: {query}",
        "request_reply_no": "❌ К сожалению, выполнить запрос нельзя: {query}",
        "request_reply_note": "📝 Сообщение: {note}",
        "request_cancel": "🗑️ Отменить запрос",
        "request_cancelled_user": "✅ Ваш запрос отменён.",
        "request_cancelled_admin": "⚠️ Пользователь отменил запрос. User ID: {user_id}\nЗапрос: {query}",
        "request_status_order": "⚠️ Сначала отметьте как 'Просмотрено'.",
        "request_status_already": "ℹ️ Этот запрос уже обновлён.",
        "request_admin_title": "📩 Book request",
        "request_admin_user": "User",
        "request_admin_user_id": "User ID",
        "request_admin_query": "Query",
        "request_admin_created": "Created",
        "request_admin_status": "Status",
        "request_admin_note": "Note",
        "request_admin_updated": "Updated",
        "request_action_seen": "👀 Seen",
        "request_action_done": "✅ Done",
        "request_action_no": "❌ No",
        "request_admin_title": "📩 Book request",
        "request_admin_user": "User",
        "request_admin_user_id": "User ID",
        "request_admin_query": "Query",
        "recent_empty": "🕘 Недавних загрузок нет.",
        "recent_title": "🕘 Недавние загрузки:",
        "favorites_empty": "⭐ Список избранного пуст.",
        "favorites_title": "⭐ Избранное:",
        "favorites_item": "• {title}",
        "favorite": "⭐ Добавить в избранное",
        "unfavorite": "❌ Удалить из избранного",
        "favorite_prompt": "⭐ Добавить эту книгу в избранное?",
        "favorited": "⭐ Добавлено в избранное.",
        "unfavorited": "❌ Удалено из избранного.",
        "referral_joined_notice": "🎉 Новый реферал!\n👤 Имя: {name}\n🕒 Время: {dt}",
        "myprofile_text": "👤 Мой профиль:\n🔎 Поиски: {searches}\n⬇️ Загрузки: {downloads}\n⭐ Избранное: {favorites}\n😃 Реакции: {reactions}\n👥 Рефералы: {referrals}\n📅 Активные дни: {active_days}\n📈 Ср/день: {avg_per_day}\n🗓️ Дата старта: {joined}\n\n💰 Монеты:\n🔎 Поиски: {coins_searches}\n⬇️ Загрузки: {coins_downloads}\n⭐ Избранное: {coins_favorites}\n😃 Реакции: {coins_reactions}\n🔗 Рефералы: {coins_referrals}\n{bonus_line}🪙 Итого: {coins_total}\n──────────\nℹ️ {ref_info}",
        "coin_bonus_line": "🎁 Бонус: {bonus}\n",
        "myprofile_ref_info": "Поделитесь ссылкой. Когда новый пользователь запускает бота по ней, вы получаете {coins_per_referral} монет за каждого реферала.",
        "share_referral_button": "🔗 Поделиться реферальной ссылкой",
        "share_referral_text": "Используй этого бота для поиска книг.",
        "top_users_more": "Показать ещё",
        "top_users_less": "Показать меньше",
        "top_users_title": "🏆 Топ пользователей",
        "top_users_empty": "❌ Список топ пользователей пуст.",
        "top_users_hint_more": "⬇️ Нажмите «Показать ещё», чтобы увидеть больше активных пользователей.",
        "top_users_footer": "👤 Откройте Мой профиль, чтобы увидеть 📊 статистику и 🪙 монеты.\n🔗 Там же можно поделиться реферальной ссылкой.\n✨ Пригласите друга по реферальной ссылке и получите больше монет.",
        "saved_indexing": "✅ Сохранено: {file} ⏳ Индексация",
        "saved_indexed": "✅ Сохранено: {file} ✅ Индексировано",
        "upload_processing": "⏳ Идет обработка файла...",
        "sending": "⏳ Отправляю книгу...",
        "sent": "✅ Отправлено.",
        "book_next_search_hint": "😊❤️ Нужна ещё книга? Просто отправьте её название напрямую.",
        "page_expired": "⚠️ Эта страница устарела. Пожалуйста, ищите снова.",
        "use_buttons": "👇 Нажмите одну из кнопок с номером ниже."
    }
}

# Inline keyboard for language selection
def get_language_keyboard():
    keyboard = [
        [InlineKeyboardButton("🇺🇿 Uzbek", callback_data="lang_uz")],
        [InlineKeyboardButton("🇬🇧 English", callback_data="lang_en")],
        [InlineKeyboardButton("🇷🇺 Russian", callback_data="lang_ru")],
    ]
    return InlineKeyboardMarkup(keyboard)
